# Basic
title: GuoJie
subtitle: 不断前行，永不止步
welcome_message: 积累从点击开始，从现在开始……
#<a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 嗨，我是郭杰，一个不断学习的iOS开发者。在追求技术的道路上，永不止步。
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 所有文章, description: archive,  url: 'http://project.onevcat.com'}
    - {title: 分类,    description: tags,      url: 'http://project.onevcat.com'}
    - {title: 关于我,  description: about,     url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: https://weibo.com/u/1612896323
    github: GuoJBlog
    twitter: 641102478Guo
    gplus: 107108267983477358170
    mail: guojie9117@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
